ds_token: YOUR_DISCORD_BOT_TOKEN
role_id: 123456789012345678 #role who can use coommands(in ds)

commmands: #test
  wlu-add: ["!wlu-add", "!wlu+"]
  wlu-del: ["!wlu-del", "!wlu-", "!wlu-remove"]
  kick: ["!kick"]

inf:
  change: "User @old has been renamed to @new and re-added to whitelist."

  subcom: "Please provide arguments for this command"
  wlu+: "+@nick in WLU"
  wlu-: "-@nick in WLU"
  kick: "@nick kicked from this server"
  ip: |
    JE: 
    ```play.example.com```
    
    BE: 
    ```play.example.pe```
  ban: "@nick was permanently banned by @staff. Reason: @reason"
  tempban: "@nick was temporarily banned by @staff for @time. Reason: @reason"
  unban: "@nick was unbanned by @staff."
  no_perm_change: ":x: Я не могу изменить ник @nick, у него слишком высокая роль!"
  no_perm_reset: ":x: Не могу сбросить ник @nick — недостаточно прав!"

ip_role_id: "123456789012345678"
ip_denied: "⛔ You need a special role to use this command."
